apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: webapp
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - nodePort: 30002
      port: 30002
  selector:
    app.kubernetes.io/instance: webapp
    app.kubernetes.io/name: webapp
  type: NodePort